name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Retrait du cache yarn car pas encore de yarn.lock
          # cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: |
          yarn install
          # Cela va créer le yarn.lock s'il n'existe pas

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test